-- ربط كل حساب بموقع ثابت يديره مسؤول النظام.

begin;

create table if not exists public.inventory_sites (
  id bigint generated by default as identity primary key,
  site_type text not null check (site_type in ('border_crossing', 'airport', 'seaport', 'dry_port', 'branch')),
  name_ar text not null,
  name_en text not null,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  constraint inventory_sites_type_name_unique unique (site_type, name_ar)
);

insert into public.inventory_sites (site_type, name_ar, name_en, sort_order) values
  ('border_crossing', 'منفذ البطحاء', 'Al Batha Border Crossing', 101),
  ('border_crossing', 'منفذ الحديثة', 'Al Haditha Border Crossing', 102),
  ('border_crossing', 'منفذ حالة عمار', 'Halat Ammar Border Crossing', 103),
  ('border_crossing', 'منفذ جديدة عرعر', 'Jadidat Arar Border Crossing', 104),
  ('border_crossing', 'منفذ الرقعي', 'Al Raqi Border Crossing', 105),
  ('border_crossing', 'منفذ الخفجي', 'Al Khafji Border Crossing', 106),
  ('border_crossing', 'منفذ سلوى', 'Salwa Border Crossing', 107),
  ('border_crossing', 'منفذ جسر الملك فهد', 'King Fahd Causeway', 108),
  ('border_crossing', 'منفذ الربع الخالي', 'Rub Al Khali Border Crossing', 109),
  ('border_crossing', 'منفذ الوديعة', 'Al Wadiah Border Crossing', 110),
  ('border_crossing', 'منفذ الطوال', 'Al Tuwal Border Crossing', 111),
  ('border_crossing', 'منفذ الخضراء', 'Al Khadra Border Crossing', 112),
  ('border_crossing', 'منفذ علب', 'Alab Border Crossing', 113),
  ('border_crossing', 'منفذ الدرة البري', 'Al Durra Border Crossing', 114),
  ('border_crossing', 'منفذ طريف البري', 'Turaif Land Border Crossing', 115),
  ('airport', 'مطار الملك خالد الدولي – الرياض', 'King Khalid International Airport', 201),
  ('airport', 'مطار الملك عبدالعزيز الدولي – جدة', 'King Abdulaziz International Airport', 202),
  ('airport', 'مطار الملك فهد الدولي – الدمام', 'King Fahd International Airport', 203),
  ('airport', 'مطار الأمير محمد بن عبدالعزيز الدولي – المدينة', 'Prince Mohammad bin Abdulaziz International Airport', 204),
  ('airport', 'مطار الأمير نايف بن عبدالعزيز الدولي – القصيم', 'Prince Naif bin Abdulaziz International Airport', 205),
  ('airport', 'مطار أبها الدولي', 'Abha International Airport', 206),
  ('airport', 'مطار الطائف الدولي', 'Taif International Airport', 207),
  ('airport', 'مطار الأمير سلطان بن عبدالعزيز – تبوك', 'Prince Sultan bin Abdulaziz Airport', 208),
  ('airport', 'مطار الأمير عبدالمحسن بن عبدالعزيز – ينبع', 'Prince Abdul Mohsin bin Abdulaziz Airport', 209),
  ('airport', 'مطار الأحساء', 'Al Ahsa Airport', 210),
  ('airport', 'مطار الجوف', 'Al Jouf Airport', 211),
  ('airport', 'مطار جازان', 'Jazan Airport', 212),
  ('airport', 'مطار حائل', 'Hail Airport', 213),
  ('airport', 'مطار نجران', 'Najran Airport', 214),
  ('airport', 'مطار شرورة', 'Sharurah Airport', 215),
  ('airport', 'مطار طريف', 'Turaif Airport', 216),
  ('airport', 'مطار القيصومة', 'Al Qaisumah Airport', 217),
  ('airport', 'مطار نيوم', 'NEOM Airport', 218),
  ('seaport', 'ميناء جدة الإسلامي', 'Jeddah Islamic Port', 301),
  ('seaport', 'ميناء الملك عبدالعزيز بالدمام', 'King Abdulaziz Port, Dammam', 302),
  ('seaport', 'ميناء الملك عبدالله', 'King Abdullah Port', 303),
  ('seaport', 'ميناء الجبيل', 'Jubail Port', 304),
  ('seaport', 'ميناء رأس الخير', 'Ras Al Khair Port', 305),
  ('seaport', 'ميناء رأس تنورة', 'Ras Tanura Port', 306),
  ('seaport', 'ميناء الخفجي', 'Khafji Port', 307),
  ('seaport', 'ميناء ينبع', 'Yanbu Port', 308),
  ('seaport', 'ميناء ضباء', 'Duba Port', 309),
  ('seaport', 'ميناء جازان', 'Jazan Port', 310),
  ('seaport', 'ميناء فرسان', 'Farasan Port', 311),
  ('seaport', 'ميناء بيش', 'Baish Port', 312),
  ('seaport', 'ميناء بترو رابغ', 'Petro Rabigh Port', 313),
  ('dry_port', 'جمرك الرياض – الميناء الجاف', 'Riyadh Dry Port Customs', 401),
  ('branch', 'الإدارة العامة – المغرزات', 'ZATCA Headquarters – Al Mughrizat', 501),
  ('branch', 'الإدارة العامة – مبنى صميم', 'ZATCA Headquarters – Sameem Building', 502),
  ('branch', 'فرع الرياض – المروج', 'Riyadh Branch – Al Muruj', 503),
  ('branch', 'فرع الرياض – النفل', 'Riyadh Branch – Al Nafal', 504),
  ('branch', 'فرع جدة', 'Jeddah Branch', 505),
  ('branch', 'فرع مكة المكرمة', 'Makkah Branch', 506),
  ('branch', 'فرع المدينة المنورة', 'Madinah Branch', 507),
  ('branch', 'فرع الدمام', 'Dammam Branch', 508),
  ('branch', 'فرع الأحساء', 'Al Ahsa Branch', 509),
  ('branch', 'فرع حفر الباطن', 'Hafr Al Batin Branch', 510),
  ('branch', 'فرع القصيم', 'Qassim Branch', 511),
  ('branch', 'فرع حائل', 'Hail Branch', 512),
  ('branch', 'فرع الجوف', 'Al Jouf Branch', 513),
  ('branch', 'فرع عرعر', 'Arar Branch', 514),
  ('branch', 'فرع تبوك', 'Tabuk Branch', 515),
  ('branch', 'فرع ينبع', 'Yanbu Branch', 516),
  ('branch', 'فرع الطائف', 'Taif Branch', 517),
  ('branch', 'فرع الباحة', 'Al Baha Branch', 518),
  ('branch', 'فرع أبها', 'Abha Branch', 519),
  ('branch', 'فرع جازان', 'Jazan Branch', 520),
  ('branch', 'فرع نجران', 'Najran Branch', 521)
on conflict (site_type, name_ar) do update
set name_en = excluded.name_en,
    sort_order = excluded.sort_order,
    is_active = true;

alter table public.assets drop constraint if exists assets_site_type_check;
alter table public.assets add constraint assets_site_type_check
  check (site_type in ('', 'border_crossing', 'airport', 'seaport', 'dry_port', 'branch', 'other'));

create table if not exists public.app_admin_emails (
  email text primary key check (email = lower(email)),
  created_at timestamptz not null default now()
);

insert into public.app_admin_emails (email)
values (lower('Khalbalawi@hotmail.com'))
on conflict (email) do nothing;

create table if not exists public.user_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  display_name text not null default '',
  role text not null default 'user' check (role in ('admin', 'user')),
  site_type text check (site_type is null or site_type in ('border_crossing', 'airport', 'seaport', 'dry_port', 'branch', 'other')),
  site_name text check (site_name is null or char_length(site_name) <= 120),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint user_profiles_site_pair_check check (
    (site_type is null and site_name is null)
    or (nullif(trim(site_type), '') is not null and nullif(trim(site_name), '') is not null)
  )
);

-- اربط أي سجلات قديمة بلا موقع بالموقع الأكثر استخداماً في حسابها.
with ranked_sites as (
  select
    user_id,
    site_type,
    site_name,
    row_number() over (partition by user_id order by count(*) desc, max(scanned_at) desc) as position
  from public.assets
  where nullif(trim(site_type), '') is not null
    and nullif(trim(site_name), '') is not null
  group by user_id, site_type, site_name
), preferred_sites as (
  select user_id, site_type, site_name
  from ranked_sites
  where position = 1
)
update public.assets as asset
set site_type = preferred.site_type,
    site_name = preferred.site_name
from preferred_sites as preferred
where asset.user_id = preferred.user_id
  and asset.site_type = ''
  and asset.site_name = '';

-- أنشئ ملفات للحسابات الحالية من موقع أجهزتها الفعلي.
with ranked_sites as (
  select
    user_id,
    site_type,
    site_name,
    row_number() over (partition by user_id order by count(*) desc, max(scanned_at) desc) as position
  from public.assets
  where nullif(trim(site_type), '') is not null
    and nullif(trim(site_name), '') is not null
  group by user_id, site_type, site_name
), preferred_sites as (
  select user_id, site_type, site_name
  from ranked_sites
  where position = 1
)
insert into public.user_profiles (user_id, email, display_name, role, site_type, site_name)
select
  auth_user.id,
  lower(auth_user.email),
  coalesce(auth_user.raw_user_meta_data ->> 'display_name', split_part(auth_user.email, '@', 1), ''),
  case when exists (
    select 1 from public.app_admin_emails admin_email
    where admin_email.email = lower(auth_user.email)
  ) then 'admin' else 'user' end,
  preferred.site_type,
  preferred.site_name
from auth.users auth_user
left join preferred_sites preferred on preferred.user_id = auth_user.id
where auth_user.email is not null
on conflict (user_id) do update
set email = excluded.email,
    display_name = case when public.user_profiles.display_name = '' then excluded.display_name else public.user_profiles.display_name end,
    role = excluded.role,
    site_type = coalesce(public.user_profiles.site_type, excluded.site_type),
    site_name = coalesce(public.user_profiles.site_name, excluded.site_name),
    updated_at = now();

create or replace function public.handle_inventory_user_profile()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.email is null then
    return new;
  end if;

  insert into public.user_profiles (user_id, email, display_name, role)
  values (
    new.id,
    lower(new.email),
    coalesce(new.raw_user_meta_data ->> 'display_name', split_part(new.email, '@', 1), ''),
    case when exists (
      select 1 from public.app_admin_emails admin_email
      where admin_email.email = lower(new.email)
    ) then 'admin' else 'user' end
  )
  on conflict (user_id) do update
  set email = excluded.email,
      display_name = excluded.display_name,
      role = excluded.role,
      updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_auth_user_created_inventory_profile on auth.users;
create trigger on_auth_user_created_inventory_profile
after insert or update of email, raw_user_meta_data on auth.users
for each row execute procedure public.handle_inventory_user_profile();

create or replace function public.is_inventory_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.user_profiles profile
    where profile.user_id = (select auth.uid())
      and profile.role = 'admin'
  );
$$;

alter table public.inventory_sites enable row level security;
alter table public.user_profiles enable row level security;
alter table public.app_admin_emails enable row level security;

drop policy if exists inventory_sites_read_authenticated on public.inventory_sites;
create policy inventory_sites_read_authenticated on public.inventory_sites
for select to authenticated using (is_active = true);

drop policy if exists user_profiles_read_own_or_admin on public.user_profiles;
create policy user_profiles_read_own_or_admin on public.user_profiles
for select to authenticated
using ((select auth.uid()) = user_id or public.is_inventory_admin());

grant select on public.inventory_sites to authenticated;
grant select on public.user_profiles to authenticated;
grant select, insert, update, delete on public.inventory_sites to service_role;
grant select, insert, update, delete on public.user_profiles to service_role;
grant select on public.app_admin_emails to service_role;
grant execute on function public.is_inventory_admin() to authenticated;

revoke all on public.app_admin_emails from anon, authenticated;
revoke all on function public.handle_inventory_user_profile() from public;

commit;
